import numpy as np
import pandas as pd
import pytest
from datatrust.models import (
    TaskType,
    QualityDimension,
    CANONICAL_QUALITY_DIMENSIONS,
    DIMENSION_CODES,
    DimensionResult,
    RemediationDecision
)
from datatrust.reproducibility import canonicalize_index, hash_index
from datatrust.remediator import DataRemediator, ACTION_REGISTRY
from datatrust.optimizer import RemediationOptimizer
from datatrust.engine import DataTrustEngine


def test_canonical_index_hashing():
    """Verify deterministic SHA-256 index hashing across numpy, pandas, and python int types."""
    py_list = [10, 25, 42, 95]
    np_int64_arr = np.array([10, 25, 42, 95], dtype=np.int64)
    np_int32_arr = np.array([10, 25, 42, 95], dtype=np.int32)
    pd_idx = pd.Index([10, 25, 42, 95])

    # 1. Identical index values with different types must produce identical hash
    hash_py = hash_index(py_list)
    hash_np64 = hash_index(np_int64_arr)
    hash_np32 = hash_index(np_int32_arr)
    hash_pd = hash_index(pd_idx)

    assert hash_py == hash_np64 == hash_np32 == hash_pd, "Hash divergence across scalar integer types"

    # 2. Canonicalize function returns standard python int
    canonical = canonicalize_index(np_int64_arr)
    assert all(type(x) is int for x in canonical)

    # 3. Different order produces different hash (sequence order matters in splits)
    hash_rev = hash_index([95, 42, 25, 10])
    assert hash_py != hash_rev

    # 4. Adding or removing elements produces different hash
    hash_mod = hash_index([10, 25, 42])
    assert hash_py != hash_mod


def test_action_authoritative_remediation():
    """Verify that only requested actions execute and unrequested actions are strictly skipped."""
    # Create dataset with > 10 rows, extreme outliers, and missing values
    vals1 = [float(i) for i in range(25)]
    vals1[3] = 100000.0
    vals1[4] = np.nan
    vals2 = [float(i * 10) for i in range(25)]
    vals2[5] = np.nan
    df = pd.DataFrame({
        "feature1": vals1,
        "feature2": vals2,
        "target": [float(i) for i in range(25)]
    })

    # Only request winsorize_outliers (do NOT request impute_median)
    cleaned_df, log = DataRemediator.apply_remediations(
        df=df,
        task=TaskType.SUPERVISED_REGRESSION,
        action_ids=["winsorize_outliers"],
        target_column="target"
    )

    # Outliers should be clipped
    assert cleaned_df["feature1"].max() < 100000.0
    # Missing values should NOT be imputed because impute_median was not requested
    assert cleaned_df["feature1"].isna().sum() == 1
    assert cleaned_df["feature2"].isna().sum() == 1

    # Log should record executed winsorization but NOT imputation
    assert any("winsorize_outliers" in item for item in log)
    assert not any("impute_median" in item for item in log)

    # Verify drop_unlabelled_target drops unlabelled rows
    df_unlab = pd.DataFrame({"feat": [1.0, 2.0, 3.0, 4.0], "target": [10.0, np.nan, 30.0, np.nan]})
    rem_unlab, log_unlab = DataRemediator.apply_remediations(
        df=df_unlab,
        task=TaskType.SUPERVISED_REGRESSION,
        action_ids=["drop_unlabelled_target"],
        target_column="target"
    )
    assert len(rem_unlab) == 2
    assert rem_unlab["target"].isna().sum() == 0
    assert any("drop_unlabelled_target" in item for item in log_unlab)

    # Verify drop_high_null_columns drops >40% null columns
    df_sparse = pd.DataFrame({
        "dense": [1.0, 2.0, 3.0, 4.0, 5.0],
        "sparse": [1.0, np.nan, np.nan, np.nan, 5.0],
        "target": [10.0, 20.0, 30.0, 40.0, 50.0]
    })
    rem_sparse, log_sparse = DataRemediator.apply_remediations(
        df=df_sparse,
        task=TaskType.SUPERVISED_REGRESSION,
        action_ids=["drop_high_null_columns"],
        target_column="target"
    )
    assert "sparse" not in rem_sparse.columns
    assert "dense" in rem_sparse.columns
    assert any("drop_high_null_columns" in item for item in log_sparse)


def test_action_registry_metadata():
    """Verify the formal action registry contains required operational metadata and matches optimizer output."""
    assert len(ACTION_REGISTRY) >= 8
    required_actions = [
        "sort_timestamps", "drop_leakage_columns", "winsorize_outliers",
        "resample_imbalance", "impute_median", "drop_redundant_identifiers",
        "drop_unlabelled_target", "drop_high_null_columns"
    ]
    for act in required_actions:
        assert act in ACTION_REGISTRY
        meta = ACTION_REGISTRY[act]
        assert meta.action_type == act
        assert meta.operational_cost in range(1, 6)
        assert len(meta.affected_dimensions) > 0
        assert len(meta.train_test_safety_policy) > 0

    # Invariant: Every remediation action generated by RemediationOptimizer must be in ACTION_REGISTRY
    sim_dimensions = {
        QualityDimension.CONSISTENCY: DimensionResult(
            dimension=QualityDimension.CONSISTENCY,
            score=40.0,
            weight=0.2,
            weighted_score=8.0,
            summary="Target leakage suspect detected",
            raw_metrics={"target_leakage_suspects": [{"feature": "leak_feat", "correlation": 0.99}]}
        ),
        QualityDimension.TIMELINESS: DimensionResult(
            dimension=QualityDimension.TIMELINESS,
            score=30.0,
            weight=0.3,
            weighted_score=9.0,
            summary="Non-monotonic and duplicate timestamps",
            raw_metrics={"is_monotonic_increasing": False, "duplicate_timestamps": 5}
        ),
        QualityDimension.DISTRIBUTION_BALANCE: DimensionResult(
            dimension=QualityDimension.DISTRIBUTION_BALANCE,
            score=35.0,
            weight=0.2,
            weighted_score=7.0,
            summary="Severe class imbalance",
            raw_metrics={"is_severely_imbalanced": True, "imbalance_ratio": 50.0}
        ),
        QualityDimension.VALIDITY: DimensionResult(
            dimension=QualityDimension.VALIDITY,
            score=50.0,
            weight=0.1,
            weighted_score=5.0,
            summary="Missing target labels",
            raw_metrics={"target_missing_rate": 0.15}
        ),
        QualityDimension.OUTLIER_ANOMALY: DimensionResult(
            dimension=QualityDimension.OUTLIER_ANOMALY,
            score=50.0,
            weight=0.1,
            weighted_score=5.0,
            summary="Heavy tail outliers",
            raw_metrics={"heavy_kurtosis_count": 2}
        ),
        QualityDimension.COMPLETENESS: DimensionResult(
            dimension=QualityDimension.COMPLETENESS,
            score=50.0,
            weight=0.1,
            weighted_score=5.0,
            summary="Missing values and high null columns",
            raw_metrics={"missing_rate": 0.10, "high_missing_cols": ["col_sparse"]}
        )
    }

    for task in TaskType:
        actions = RemediationOptimizer.optimize_remediations(
            task=task,
            dimensions=sim_dimensions,
            current_trust_score=50.0,
            is_vetoed=True
        )
        for a in actions:
            assert a.action_type in ACTION_REGISTRY, f"Optimizer action '{a.action_type}' not in ACTION_REGISTRY"


def test_remediation_decision_outcomes():
    """Verify RemediationDecision states and closed-loop validation."""
    # Test 1: Dataset C with timestamp duplicates and temporal disorder
    # Holdout test set preserves sensor collisions under immutability -> decision should be BLOCKED
    rng = np.random.RandomState(42)
    n = 100
    base_dates = pd.date_range("2024-01-01", periods=n, freq="D").tolist()
    # Inject duplicate timestamps
    base_dates[10] = base_dates[9]
    base_dates[25] = base_dates[24]
    base_dates[75] = base_dates[74]
    base_dates[85] = base_dates[84]

    shuffle_idx = rng.permutation(n)
    df_ts = pd.DataFrame({
        "timestamp": [base_dates[i] for i in shuffle_idx],
        "val": rng.normal(10, 2, n),
        "target": np.linspace(0, 50, n) + rng.normal(0, 1, n)
    })

    _, report_after, val_res = DataTrustEngine.remediate_and_validate(
        df=df_ts,
        task=TaskType.TIME_SERIES_FORECASTING,
        target_column="target",
        time_column="timestamp"
    )

    # In post-remediation on full concatenated dataset (train sorted + test untouched),
    # test duplicates remain, preserving RED veto tier
    assert val_res.decision in [RemediationDecision.BLOCKED, RemediationDecision.REVIEW_REQUIRED]
    assert "remediation" in val_res.decision_reason.lower() or "blocked" in val_res.decision_reason.lower()


def test_eight_canonical_quality_dimensions_and_codes():
    """Verify all 8 canonical dimensions and their 3-letter codes."""
    assert len(CANONICAL_QUALITY_DIMENSIONS) == 8
    expected_codes = {
        QualityDimension.COMPLETENESS: "CMP",
        QualityDimension.VALIDITY: "VAL",
        QualityDimension.CONSISTENCY: "CNS",
        QualityDimension.UNIQUENESS: "UNQ",
        QualityDimension.TIMELINESS: "TIM",
        QualityDimension.OUTLIER_ANOMALY: "OUT",
        QualityDimension.DISTRIBUTION_BALANCE: "BAL",
        QualityDimension.COVERAGE_REPRESENTATIVENESS: "COV"
    }
    for dim, code in expected_codes.items():
        assert DIMENSION_CODES[dim] == code
